name: Check Markdown Links
on: [pull_request, push]
jobs:
  check-links:
    name: runner / linkspector
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run Linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          reporter: github-check
          config_file: .linkspector.yml
