exclude:
  # ignore relative paths
  - '^(\./|\../|/)'

dirs:
  - .
httpHeaders:
  - url: '^https://www\\.raspberrypi\\.com/.*'
    headers:
      - 'User-Agent: Mozilla/5.0'
      - 'Accept: text/html,*/*'
      - 'Accept-Language: en'
followRedirects: 'all'
aliveStatusCodes:
  - 200
  - 206
  - 301
  - 302
  - 307
  - 308
